app/routes.php
<?php

Route::get('/', 'HomePageController@index');

// Confide routes
Route::get('register', 					['uses' => 'UsersController@create', 'name' => 'register']);
Route::post('register', 				'UsersController@store');

Route::get('login', 					'UsersController@login');
Route::post('login', 					'UsersController@doLogin');

Route::get('users/confirm/{code}', 		'UsersController@confirm');
Route::get('forgot_password', 			'UsersController@forgotPassword');
Route::post('forgot_password', 			'UsersController@doForgotPassword');
Route::get('reset_password/{token}', 	'UsersController@resetPassword');
Route::post('reset_password', 			'UsersController@doResetPassword');

// Main Application
Route::group(['before' => 'auth'], function(){
	Route::get('logout', 		'UsersController@logout');

	Route::get('account', 		'AccountController@index');
	Route::post('account', 		'AccountController@post');
	Route::resource('project', 	'ProjectsController');
	Route::get('projects', 		'ProjectsController@index');

	Route::resource('project.issue', 	'ProjectIssueController');
});

Route::when('*', 'csrf', array('post', 'put', 'delete'));

// Composers 
View::composer('partials.nav', 'MenuComposer');

app/models/Project.php
<?php

class Project extends Eloquent{

	protected $guarded = ['id', 'user_id'];
	
}

app/controllers/ProjectsController.php
<?php

class ProjectsController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$userId 	= Auth::id();
		$projects 	= Project::where('user_id', '=', $userId)->paginate(10);

		return View::make('main_app.project.projects')->withProjects($projects);
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('main_app.new_project');
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$userId = Auth::id();

		$github_project = Input::get('github');
		$github_address = 'http://github.com/' . $github_project;

		Input::merge(['github' => $github_address]);

		//dd(Input::all());

		$rules = [
			'name' => 'required',
			'url' => 'url',
			'github' => 'url|required'
		];

		$validator = Validator::make(Input::all(), $rules);

		if($validator->fails()){
			$messages = $validator->messages();
			return View::make('main_app.new_project')->withErrors($messages)->withInput(Input::all());
		}

		$project 				= new Project;
		$project->user_id 		= $userId;
		$project->name 			= Input::get('name');
		$project->desc 			= Input::get('desc');
		$project->url 			= Input::get('url');
		$project->github_url 	= Input::get('github');
		$project->save();


		Session::flash('success', 'Project added successfully');
		return Redirect::to('/projects');
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$issues 	= Issue::where('project_id', '=', $id)->paginate(10);
		$issueCount = Issue::where('project_id', '=', $id)->count();
		$project 	= Project::find($id);
		return View::make('main_app.project.project')
			->withProject($project)
			->withIssues($issues)
			->withIssue_count($issueCount);
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$project = Project::find($id);

		return View::make('main_app.project.edit')->withProject($project);

	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$rules = [
			'name' => 'required',
			'url' => 'url',
			'github' => 'url|required'
		];

		$validator = Validator::make($rules, Input::all());

		if($validator->fails()){
			$messages = $validator->messages();
			return View::make('main_app.edit')->withErrors($messages)->withInput(Input::all());
		}

		$project = Project::find($id);

		$project->name 			= Input::get('name');
		$project->url 			= Input::get('url');
		$project->github_url	= Input::get('name');
		$project->desc			= Input::get('desc');
		$project->save();

		Session::flash('success', 'Changes saved successfully');
		return Redirect::to('/projects');
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$project = Project::find($id);

		$project->delete();

		Session::flash('success', 'Project deleted successfully');
		return Redirect::to('/projects');

	}


}

app/views/main_app/project/edit.blade.php
@extends('layouts.main')

@section('styles')
<style type="text/css">
	#main{
		max-width: 400px;
		padding-top: 80px;
	}
</style>
@stop


@section('content')

<div class="container" id="main">
	{{ Form::model($project, ['method' => 'put', 'route' => ['project.update', $project->id]]) }}


			<h2>Edit Project</h2>

			<div class="form-group">
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-pencil"></i></span>
					{{ Form::text('name', NULL, [
						'class' 		=> 'form-control',
						'placeholder' 	=> 'Project Name'
						]) }}
				</div>
			</div>

			<div class="form-group">
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-link"></i></span>
					{{ Form::text('url', NULL, [
						'class' 		=> 'form-control',
						'placeholder' 	=> 'Project URL',
						]) }}
				</div>
			</div>

			<div class="form-group">
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-github"></i></span>
					{{ Form::text('github_url', NULL, ['class' => 'form-control', 
						'placeholder' => 'GitHub Link (example/example)']) }}
				</div>
			</div>

			<div class="form-group">
				{{ Form::textarea('desc', NULL, [
					'class'			=> 'form-control', 
					'placeholder' 	=> 'Description'
					]) 
				}}
			</div>

			<div class="form-group">
				{{ Form::submit('Save Changes', ['class' => 'btn btn-primary btn-lg btn-block']) }}
			</div>

	{{ Form::close() }}

	{{ Form::open(['method' => 'delete', 'route' => ['project.destroy', $project->id]]) }}

		{{ Form::submit('Delete', ['class' => 'btn btn-danger btn-lg btn-block']) }}

	{{ Form::close() }}

</div>

@stop

app/views/main_app/project/project.blade.php
@extends('layouts.main')

@section('styles')
<style type="text/css">
	#main{
		max-width: 450px;
		padding-top: 80px;
	}
	h2{
		text-align: center;
	}
	.item{
		border: 3px solid #34a0c7;
		border-radius: 10px;
		margin: 20px 0px;
	}
	.item h3{
		margin: 0px;
		margin: 10px 20px;
	}
	.item p{
		margin: 0px;
		margin: 10px 20px;
	}
	#issues{
		padding: 10px 0px; 
		text-align: center;
	}
</style>
@stop

@section('content')
	<div class="container" id="main">	

		<h2>Issues related to {{{$project->name}}}</h2>

		<div class="text-center">
			<a class="btn btn-success" href="{{ route('project.issue.create', $project->id) }}">Add New Project</a>
		</div>

		@if($issue_count > 0)
			@foreach($issues as $issue)
				<div class="item">
					<div class="row">
						<div class="col-md-8"><h3>{{{$issue->title}}}</h3></div>
						<div class="col-md-4"><a class="btn btn-default" href="{{ route('project.issue.edit', [$project->id, $issue->id]) }}">Edit Project</a></div>
					</div>
					<p>{{{ $issue->desc }}}</p>
				</div>
			@endforeach
		@else
			<p id="issues">No issues to show.</p>
		@endif
		<div class="text-center">
			{{ $issues->links(); }}
		</div>
	</div>

@stop

app/views/main_app/project/projects.blade.php
@extends('layouts.main')

@section('styles')
	<style type="text/css">
		#main{
			max-width: 400px;
			padding-top: 80px;
		}
		.item{
			border: 3px solid #34a0c7;
			border-radius: 10px;
			margin: 20px 0px;
		}
		.item h3{
			margin: 0px;
			margin: 10px 20px;
		}
		.item p{
			margin: 0px;
			margin: 10px 20px;
		}
		.edit{
			margin-right: 10px;
			margin-top: 5px;
		}
	</style>
@stop


@section('content')
	
	<div class="container" id="main">
		@foreach ($projects as $project)
			<div class="item">
				<div class="row">
					<div class="col-md-8">
						<h3><a href="/project/{{{ $project->id }}}">{{{$project->name}}}</a></h3>
					</div>
					<div class="col-md-4">
						<a href="/project/{{{ $project->id }}}/edit/" class="btn btn-default edit">
							Edit Project
						</a>
					</div>
				</div>
				<p>{{{ $project->desc }}}</p>
				@if($project->github_url != NULL)
					<p>
						<i class="fa fa-github"></i>&nbsp;
						<a href="{{{ $project->github_url }}}">
							{{{ $project->github_url }}}
						</a>
					</p>
				@endif

				@if($project->url != NULL)
					<p>
						<i class="fa fa-link"></i>&nbsp;
						<a href="{{{ $project->url }}}">
							{{{ $project->url }}}
						</a>
					</p>
				@endif
			</div>
		@endforeach
		<div class="text-center">
			{{ $projects->links(); }}
		</div>
	</div>
@stop


@section('scripts')
	@if (Session::get('success'))
		@section('scripts')
			<script type="text/javascript">
				new notif({
					type: "success",
					msg: "Changes saved successfully",
					position: "right",
					autohide: false,
					multiline: true
				});
			</script>
		@stop
	@endif
@stop